// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUlvvDP2z41uA0V7_WLML2c0KuDKYN2ZA',
    appId: '1:210354035049:web:aa5b94d39d1e864e4ac5f8',
    messagingSenderId: '210354035049',
    projectId: 'arzu-chat',
    authDomain: 'arzu-chat.firebaseapp.com',
    storageBucket: 'arzu-chat.appspot.com',
    measurementId: 'G-47T7DJ24L5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5eaQpbsqHJs_mjFNf4NHCINBRUhoFXhc',
    appId: '1:210354035049:android:932e2f5efbcbe4554ac5f8',
    messagingSenderId: '210354035049',
    projectId: 'arzu-chat',
    storageBucket: 'arzu-chat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJmFb_n8fTOlzXSDSo1ArxBaNuX6VZ2b4',
    appId: '1:210354035049:ios:3f08885ed70881224ac5f8',
    messagingSenderId: '210354035049',
    projectId: 'arzu-chat',
    storageBucket: 'arzu-chat.appspot.com',
    iosClientId: '210354035049-4bb7donc1efh7mntnu67sh0j3k4o7g9l.apps.googleusercontent.com',
    iosBundleId: 'com.example.arzuChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJmFb_n8fTOlzXSDSo1ArxBaNuX6VZ2b4',
    appId: '1:210354035049:ios:a2277be752e4581f4ac5f8',
    messagingSenderId: '210354035049',
    projectId: 'arzu-chat',
    storageBucket: 'arzu-chat.appspot.com',
    iosClientId: '210354035049-l5rrhggejl7bi24vsmt7gkpmn7egt6gk.apps.googleusercontent.com',
    iosBundleId: 'com.example.arzuChat.RunnerTests',
  );
}
